INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (1, '부산도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (2, '서울도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (3, '안양도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (4, '안산도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (5, '대구도서관');

INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (6, '경기도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (7, '대전도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (8, '강원도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (9, '인천도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (10, '창원도서관');