INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (1, 1, '해리포터','스네이프','A출판사', 'BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (1, 2, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (1, 3, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (1, 4, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (1, 5, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');

INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (2, 6, '해리포터','스네이프','A출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (2, 7, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (2, 8, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (2, 9, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (2, 10, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');

INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (3, 11, '해리포터','스네이프','A출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (3, 12, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (3, 13, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (3, 14, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (3, 15, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');

INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (4, 16, '해리포터','스네이프','A출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (4, 17, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (4, 18, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (4, 19, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (4, 20, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');

INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (5, 21, '해리포터','스네이프','A출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (5, 22, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (5, 23, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (5, 24, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
INSERT INTO book (LIBRARY_ID, BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (5, 25, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');




--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (1, '해리포터','스네이프','A출판사', 'BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (2, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (3, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (4, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (5, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');
--
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (6, '해리포터','스네이프','A출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (7, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (8, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (9, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (10, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');
--
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (11, '해리포터','스네이프','A출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (12, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (13, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (14, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (15, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');
--
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (16, '해리포터','스네이프','A출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (17, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (18, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (19, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (20, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');
--
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (21, '해리포터','스네이프','A출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (22, '삼국지','관우','B출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (23, '반지의제왕','간달프','C출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (24, '클린코드','로버트 C','D출판사','BOOK_STATUS_AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (25, '커리어스킬','존손메즈','E출판사','BOOK_STATUS_AVAILABLE');