--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (1, '해리포터','스네이프','A출판사', 'AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (2, '삼국지','관우','B출판사','AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (3, '반지의제왕','간달프','C출판사','AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (4, '클린코드','로버트 C','D출판사','AVAILABLE');
--INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_STATUS) VALUES (5, '커리어스킬','존손메즈','E출판사','AVAILABLE');


INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER) VALUES (1, '해리포터','스네이프','A출판사');
INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER) VALUES (2, '삼국지','관우','B출판사');
INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER) VALUES (3, '반지의제왕','간달프','C출판사');
INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER) VALUES (4, '클린코드','로버트 C','D출판사');
INSERT INTO book (BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER) VALUES (5, '커리어스킬','존손메즈','E출판사');