INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (1, '부산도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (2, '서울도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (3, '안양도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (4, '안산도서관');
INSERT INTO library (LIBRARY_ID, LIBRARY_NAME) VALUES (5, '대구도서관');