--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (1, 1, 1);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (2, 2, 1);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (3, 3, 1);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (4, 4, 1);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (5, 5, 1);
--
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (6, 1, 2);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (7, 2, 2);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (8, 3, 2);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (9, 4, 2);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (10, 5, 2);
--
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (11, 1, 3);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (12, 2, 3);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (13, 3, 3);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (14, 4, 3);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (15, 5, 3);
--
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (16, 1, 4);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (17, 2, 4);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (18, 3, 4);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (19, 4, 4);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (20, 5, 4);
--
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (21, 1, 5);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (22, 2, 5);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (23, 3, 5);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (24, 4, 5);
--INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID) VALUES (25, 5, 5);


INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (1, 1, 1, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (2, 2, 1, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (3, 3, 1, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (4, 4, 1, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (5, 5, 1, 'AVAILABLE');

INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (6, 1, 2, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (7, 2, 2, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (8, 3, 2, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (9, 4, 2, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (10, 5, 2, 'AVAILABLE');

INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (11, 1, 3, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (12, 2, 3, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (13, 3, 3, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (14, 4, 3, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (15, 5, 3, 'AVAILABLE');

INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (16, 1, 4, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (17, 2, 4, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (18, 3, 4, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (19, 4, 4, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (20, 5, 4, 'AVAILABLE');

INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (21, 1, 5, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (22, 2, 5, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (23, 3, 5, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (24, 4, 5, 'AVAILABLE');
INSERT INTO library_book (LIBRARY_BOOK_ID, BOOK_ID, LIBRARY_ID, BOOK_STATUS) VALUES (25, 5, 5, 'AVAILABLE');

