spring:
# JUnit Test 전용 H2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  실제 DB 사용 전용

#  datasource:
#    url: jdbc:mysql://localhost:3306/bookapi
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: pw1234
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
##      ddl-auto: create
#      ddl-auto: update
##      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  sql:
#    init:
#      mode: never
##      mode: always
##      mode: never
#      encoding: UTF-8
#      separator: ";"
#      data-locations: classpath:/db/*

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:
    admin: admin@gmail.com

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420