spring:
## JUnit Repository Test 전용 H2
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#  실제 DB 사용 전용
  datasource:
    # jdbc:mysql://<hostname>:<port>/<database>
    # hostname : DB 서버의 호스트 이름이나 IP 주소 입력.
    # 컨테이너 사용할 때는 컨테이너 이름 입력
    # port : MySQL 서버가 실행중인 포트 번호, MySQL 컨테이너 생성 시 작성 코드 우항.
    # MySQL 컨테이너 생성할 때 작성한 좌항은 Docker가 실행중인 PC의 DB 포트.
    # database : 연결할 DB의 이름.
    url: jdbc:mysql://mysql-container:3306/mysql-container
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pw1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
#      ddl-auto: update
#      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
#      mode: never
      mode: always
#      mode: never
      encoding: UTF-8
      separator: ";"
      data-locations: classpath:/db/*

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:
    admin: admin@gmail.com

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420